# Generated by Django 4.2 on 2023-05-20 03:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0007_alter_bulletin_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=99, null=True)),
                ('title', models.CharField(max_length=49, null=True)),
                ('role', models.CharField(max_length=99, null=True)),
                ('organization', models.CharField(max_length=99, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='bulletin',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 20, 3, 9, 51, 341983, tzinfo=datetime.timezone.utc)),
        ),
    ]
