# Generated by Django 4.2 on 2023-05-24 14:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0008_person_alter_bulletin_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=399, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='')),
                ('img_url', models.ImageField(blank=True, null=True, upload_to='')),
                ('news_link', models.TextField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='bulletin',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 24, 14, 35, 9, 923208, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='person',
            name='role',
            field=models.CharField(blank=True, max_length=99, null=True),
        ),
    ]
