# Generated by Django 4.2 on 2023-05-24 23:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0010_archive_alter_bulletin_created_alter_news_news_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='bulletin',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 24, 23, 57, 21, 729672, tzinfo=datetime.timezone.utc)),
        ),
    ]
