# Generated by Django 4.2 on 2023-05-25 00:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0011_sharedmodel_alter_bulletin_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedmodel',
            name='name',
            field=models.CharField(blank=True, max_length=99, null=True),
        ),
        migrations.AlterField(
            model_name='bulletin',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 25, 0, 0, 37, 555745, tzinfo=datetime.timezone.utc)),
        ),
    ]
