# Generated by Django 4.2 on 2023-05-25 00:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0012_sharedmodel_name_alter_bulletin_created'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SharedModel',
            new_name='Status',
        ),
        migrations.AlterField(
            model_name='bulletin',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 25, 0, 16, 23, 472120, tzinfo=datetime.timezone.utc)),
        ),
    ]
