# Generated by Django 4.2 on 2023-06-04 22:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0013_rename_sharedmodel_status_alter_bulletin_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=399)),
                ('location', models.CharField(max_length=99)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('date_start', models.DateField(null=True)),
                ('date_end', models.DateField(null=True)),
                ('month_start', models.DateField(null=True)),
                ('month_end', models.DateField(null=True)),
                ('img_url', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_content', models.BooleanField()),
                ('event_link', models.TextField(blank=True, null=True)),
                ('event_description', models.TextField(blank=True, null=True)),
                ('blog_post', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='bulletin',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 4, 22, 19, 39, 209436, tzinfo=datetime.timezone.utc)),
        ),
    ]
