# Generated by Django 4.2 on 2023-06-04 22:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0014_slidercontent_alter_bulletin_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulletin',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 4, 22, 21, 23, 644183, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='slidercontent',
            name='month_end',
            field=models.CharField(max_length=39, null=True),
        ),
        migrations.AlterField(
            model_name='slidercontent',
            name='month_start',
            field=models.CharField(max_length=39, null=True),
        ),
    ]
