# Generated by Django 4.2 on 2023-06-04 22:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0015_alter_bulletin_created_alter_slidercontent_month_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slidercontent',
            name='pdf_content',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='slidercontent',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='bulletin',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 4, 22, 26, 9, 610083, tzinfo=datetime.timezone.utc)),
        ),
    ]
