# Generated by Django 4.2 on 2023-06-04 22:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0016_slidercontent_pdf_content_slidercontent_pdf_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulletin',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 4, 22, 30, 1, 39193, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='slidercontent',
            name='location',
            field=models.CharField(blank=True, max_length=99, null=True),
        ),
    ]
