# Generated by Django 4.2 on 2023-06-05 19:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0019_blogpost_author_blogpost_author_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulletin',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 5, 19, 48, 42, 936903, tzinfo=datetime.timezone.utc)),
        ),
    ]
