# Generated by Django 4.2 on 2023-06-06 21:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0021_members_workgroup_alter_bulletin_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulletin',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 6, 21, 0, 54, 87718, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='workgroup',
            name='instution',
            field=models.CharField(blank=True, max_length=399, null=True),
        ),
        migrations.AlterField(
            model_name='workgroup',
            name='location',
            field=models.CharField(blank=True, max_length=199, null=True),
        ),
    ]
