# Generated by Django 4.2 on 2023-06-06 22:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0026_workgroup_coordinator_img_alter_bulletin_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='workgroup',
            name='instution_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='bulletin',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 6, 22, 47, 53, 940951, tzinfo=datetime.timezone.utc)),
        ),
    ]
