# Generated by Django 4.2 on 2023-06-06 23:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0027_workgroup_instution_image_alter_bulletin_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='workgroup',
            name='location_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='bulletin',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 6, 23, 28, 40, 702532, tzinfo=datetime.timezone.utc)),
        ),
    ]
