# Generated by Django 4.2 on 2023-06-07 13:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0028_workgroup_location_image_alter_bulletin_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnteriorRomedInf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=99)),
                ('year', models.CharField(max_length=4)),
                ('location', models.CharField(max_length=99)),
            ],
        ),
        migrations.AlterField(
            model_name='bulletin',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 7, 13, 9, 2, 107634, tzinfo=datetime.timezone.utc)),
        ),
    ]
