# Generated by Django 4.2 on 2023-06-07 13:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0029_anteriorromedinf_alter_bulletin_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='anteriorromedinf',
            name='event_link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bulletin',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 7, 13, 22, 6, 256826, tzinfo=datetime.timezone.utc)),
        ),
    ]
