# Generated by Django 4.2 on 2023-06-07 13:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0030_anteriorromedinf_event_link_alter_bulletin_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='anteriorromedinf',
            name='event_docomuent',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='bulletin',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 7, 13, 40, 8, 960512, tzinfo=datetime.timezone.utc)),
        ),
    ]
