# Generated by Django 4.2 on 2023-06-07 13:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0031_anteriorromedinf_event_docomuent_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anteriorromedinf',
            old_name='event_docomuent',
            new_name='event_document',
        ),
        migrations.AlterField(
            model_name='bulletin',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 7, 13, 51, 34, 928097, tzinfo=datetime.timezone.utc)),
        ),
    ]
