# Generated by Django 4.2 on 2023-06-08 00:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0032_rename_event_docomuent_anteriorromedinf_event_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='archive',
            name='author_img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='bulletin',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 8, 0, 32, 24, 859466, tzinfo=datetime.timezone.utc)),
        ),
    ]
