# Generated by Django 4.2 on 2023-06-08 00:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0034_archive_author_archive_author_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='archive',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bulletin',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 8, 0, 55, 32, 472303, tzinfo=datetime.timezone.utc)),
        ),
    ]
