# Generated by Django 4.2 on 2023-06-08 02:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0035_archive_content_alter_bulletin_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='EchipaTitles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=199)),
                ('name', models.CharField(max_length=299)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('website', models.URLField(blank=True, null=True)),
                ('instution', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='bulletin',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 8, 2, 26, 28, 140917, tzinfo=datetime.timezone.utc)),
        ),
    ]
